env:
  global:
    - secure: Xy0Gsm+HY2+WEL/kV4xGaemEBZLv31we8kT5uU5tXNZxeDknRSSxCgc+dNUxAaNxO8ZY+ZBEA6mraMPnmPfEIB+EnI3n91FmOqwQnlbMG0fxOhhqtwvfX8kapS5Qjmsn50NMIY9SyjnPnlJ5W+VgedJGlr7i9yLCM4G9ZFLcfwA=
language:
  - rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh